Repository vapor/console-kit, pull requests merged in 2023-11, with the labels that each got.

#190 Fix a Sendable warning on Linux
  Sources/ConsoleKit/Activity/ActivityIndicator.swift
Labels: semver-patch

#191 Improve AnySendableHashable to match Hashable
  Sources/ConsoleKit/Terminal/Terminal.swift
  Sources/ConsoleKit/Utilities/AnySendableHashable.swift
Labels: semver-minor

#185 Elide main queue check in Linux readpassphrase() implementation
  Sources/ConsoleKit/Terminal/readpassphrase_linux.swift
Labels: semver-patch

#193 Fix `AnySendableHashable` regression
  Sources/ConsoleKit/Activity/ActivityBar.swift
  Sources/ConsoleKit/Utilities/AnySendableHashable.swift
Labels: semver-patch

#194 Add a public initializer to LogRecord
  Sources/ConsoleKit/Utilities/LoggerFragment.swift
Labels: enhancement, semver-minor
